# SPDX-FileCopyrightText: 2024 The TetriQ authors
#
# SPDX-License-Identifier: CC0-1.0

name: Website deployment

on:
  push:
    paths:
      - "www/**"
    branches:
      - main

jobs:
  deploy-website:
    name: Deploy website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy with rsync
        uses: up9cloud/action-rsync@v1.2
        env:
          HOST: ${{secrets.DEPLOY_SSH_HOST}}
          USER: ${{secrets.DEPLOY_SSH_USER}}
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          SOURCE: doc/book/
          TARGET: tetriq/
          ARGS: -avz --exclude manual/ --delete
